### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by bartes** [spirosikmd/angular2-elastic-input#40]
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule

I think it is just a ngModule setup issue

**Comment by spirosikmd** [comment]
Thank you @bartes! Yes, I need to work on the support for angular 5!

**Comment by bartes** [comment]
I guess it should be super simple. Adding `src/index.ts` with 
```export * from './xxxx.directive';
export * from './xxxxx.module'; ``` and using it inside package.json should do the job

**Comment by spirosikmd** [comment]
Hey @bartes! When I run the docs example with the latest angular I don't get an error. Everything works. How can I reproduce the issue? Does this happen in a project bootstrapped with `angular-cli`? Otherwise, I am not what to update and why? Thanks!

**Comment by bartes** [comment]
yes angular-cli ..and I guess this is a case : https://github.com/angular/angular-cli/issues/8284

**Comment by bartes** [comment]
with a bit of configuration it doesn't require a change, but angular dependency has to be changed to peerDependency one or dropped

**Comment by spirosikmd** [comment]
Thank you for the effort on testing with the cli. Reading through the comments in angular/angular-cli#8284, I think this is indeed a cli configuration issue. What do you mean by angular dependency has to be somehow untied?

**Comment by bartes** [comment]
currently it loads angular4 from within this package and I would like to have it picked up from my project.

**Comment by joschne** [comment]
After upgrading from Angular 4 to 5 I get this compilation error

`ERROR in ./node_modules/angular2-elastic-input/src/elastic-input.module.ts
Module build failed: Error: /Users/admin/Code/geovistory/client/node_modules/angular2-elastic-input/src/elastic-input.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/admin/Code/geovistory/client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/Users/admin/Code/geovistory/client/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./node_modules/angular2-elastic-input/index.js 6:9-46
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
`

Any help is appreciated, thanks!

**Comment by arun-maddheshia** [comment]
@spirosikmd any update on it ?

**Comment by spirosikmd** [comment]
@arun-maddheshia and @joschne I will look into the Angular Package format and try to update library accordingly! Expect a PR soon! Thank you for updating this issue 👍

**Comment by arun-maddheshia** [comment]
yes please its make our life easy.

**Comment by spirosikmd** [comment]
There is an issue currently with the semantic release. When this is fixed, there will be a new version!

**Comment by spirosikmd** [comment]
There is a new version [1.4.0](https://github.com/spirosikmd/angular2-elastic-input/releases/tag/v1.4.0), which fixes this issue. Please try it out and let me know if it works!

**Comment by arun-maddheshia** [comment]
@spirosikmd getting error at production build or with --aot

ERROR in Error during template compile of 'UsersModule'
  Function calls are not supported in decorators but 'ElasticInputModule' was called.

**Comment by spirosikmd** [comment]
@arun-maddheshia can you please provide a bit more information? What do you mean by production build? When I run `ng build` in the test project that uses `angular2-elastic-input` everything is working. Also, how do you use `--aot`? How can I reproduce it? Thanks!

**Comment by arun-maddheshia** [comment]
@spirosikmd i just run `ng serve --aot`

**Comment by arun-maddheshia** [comment]
@spirosikmd any update?

**Comment by spirosikmd** [comment]
Hey @arun-maddheshia! Not yet... I am not sure I will have time the following week to work on this issue. The only thing that is not working is AOT. But I guess this is an important feature to support. Please feel free to try and fix and submit a PR. I would much appreciate it!

**Comment by spirosikmd** [comment]
@arun-maddheshia @bartes @joschne this should be fixed! Please test and re-open this issue if it does not work!

**Comment by joschne** [comment]
@spirosikmd thank you, it works!

`npm i angular2-elastic-input@latest --save` 
... solved the problem for me :-)
